services:
  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "${HTTP_PORT:-80}:80"
      - "${HTTPS_PORT:-443}:443"
    volumes:
      - /sistemas/nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
      - ./nginx/ssl/letsencrypt:/etc/letsencrypt
      - ./nginx/ssl/www:/var/www/certbot
      - ./logs/nginx:/var/log/nginx
      # Mapear diretórios das aplicações em produção
      - /sistemas/apps/php84:/var/www/html/php84
      - /sistemas/apps/php74:/var/www/html/php74
      - /sistemas/apps/php56:/var/www/html/php56
    depends_on:
      - app-php84
      - app-php74
      - app-php56
    networks:
      - sistemas-network
    restart: unless-stopped

  # MySQL 8.0 (Versão mais recente)
  mysql8:
    image: mysql:8.0
    container_name: mysql8
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL8_ROOT_PASSWORD:-rootpass123}
      MYSQL_DATABASE: ${MYSQL8_DATABASE:-app_database}
      MYSQL_USER: ${MYSQL8_USER:-app_user}
      MYSQL_PASSWORD: ${MYSQL8_PASSWORD:-apppass123}
    volumes:
      - mysql8-data:/var/lib/mysql
      - mysql8-conf:/etc/mysql/conf.d
      - ./mysql/init:/docker-entrypoint-initdb.d
    ports:
      - "${MYSQL8_PORT:-3306}:3306"
    networks:
      - sistemas-network
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password

  # MySQL 5.7 (Versão legada)
  mysql57:
    image: mysql:5.7
    container_name: mysql57
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL57_ROOT_PASSWORD:-rootpass123}
      MYSQL_DATABASE: ${MYSQL57_DATABASE:-app_database}
      MYSQL_USER: ${MYSQL57_USER:-app_user}
      MYSQL_PASSWORD: ${MYSQL57_PASSWORD:-apppass123}
    volumes:
      - mysql57-data:/var/lib/mysql
      - mysql57-conf:/etc/mysql/conf.d
    ports:
      - "${MYSQL57_PORT:-3307}:3306"
    networks:
      - sistemas-network
    restart: unless-stopped

  # Aplicação com PHP 8.4
  app-php84:
    build:
      context: ./docker/php84
      dockerfile: Dockerfile
    container_name: app-php84
    volumes:
      - /sistemas/apps/php84:/var/www/html/php84
      - ./logs/php84:/var/log/php
    depends_on:
      - mysql8
    networks:
      - sistemas-network
    restart: unless-stopped
    environment:
      - PHP_VERSION=8.4

  # Aplicação com PHP 7.4
  app-php74:
    build:
      context: ./docker/php74
      dockerfile: Dockerfile
    container_name: app-php74
    volumes:
      - /sistemas/apps/php74:/var/www/html/php74
      - ./logs/php74:/var/log/php
    depends_on:
      - mysql8
    networks:
      - sistemas-network
    restart: unless-stopped
    environment:
      - PHP_VERSION=7.4

  # Aplicação com PHP 5.6 (Legado)
  app-php56:
    build:
      context: ./docker/php56
      dockerfile: Dockerfile
    container_name: app-php56
    volumes:
      - /sistemas/apps/php56:/var/www/html/php56
      - ./logs/php56:/var/log/php
    depends_on:
      - mysql57
    networks:
      - sistemas-network
    restart: unless-stopped
    environment:
      - PHP_VERSION=5.6

  # Redis para cache (opcional, mas recomendado para Laravel)
  redis:
    image: redis:7-alpine
    container_name: redis-cache
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis-data:/data
    networks:
      - sistemas-network
    restart: unless-stopped

  # Certbot para Let's Encrypt SSL
  certbot:
    image: certbot/certbot
    container_name: certbot-ssl
    volumes:
      - ./nginx/ssl/letsencrypt:/etc/letsencrypt
      - ./nginx/ssl/lib:/var/lib/letsencrypt
      - ./nginx/ssl/www:/var/www/certbot
    networks:
      - sistemas-network
    # Comando para manter container rodando
    entrypoint: /bin/sh -c 'trap exit TERM; while :; do sleep 12h & wait $${!}; done'

networks:
  sistemas-network:
    driver: bridge
    name: sistemas-network

volumes:
  mysql8-data:
  mysql57-data:
  redis-data:
  mysql8-conf:
  mysql57-conf:
